x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  ton:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ton:fixed
    pull_policy: never
    restart: unless-stopped
    tty: true
    ports:
      - "0.0.0.0:${VALIDATOR_PORT}:${VALIDATOR_PORT}/udp"
      - "0.0.0.0:${LITESERVER_PORT}:${LITESERVER_PORT}/tcp"
    volumes:
      - ton:/var/ton-work
      - mytoncore:/usr/local/bin/mytoncore
      - shared:/shared
    environment:
      PIP_BREAK_SYSTEM_PACKAGES: 1
      TON_BRANCH: ${TON_BRANCH}
      GLOBAL_CONFIG_URL: ${GLOBAL_CONFIG_URL}
      IGNORE_MINIMAL_REQS: ${IGNORE_MINIMAL_REQS}
      MYTONCTRL_VERSION: ${MYTONCTRL_VERSION}
      DUMP: ${DUMP}
      MODE: ${MODE}
      ARCHIVE_TTL: ${ARCHIVE_TTL}
      STATE_TTL: ${STATE_TTL}
      SYNC_BEFORE: ${SYNC_BEFORE}
      VERBOSITY: ${VERBOSITY}
      CUSTOM_PARAMETERS: ${CUSTOM_PARAMETERS:-}
      PUBLIC_IP: ${PUBLIC_IP}
      VALIDATOR_PORT: ${VALIDATOR_PORT}
      LITESERVER_PORT: ${LITESERVER_PORT}
      VALIDATOR_CONSOLE_PORT: ${VALIDATOR_CONSOLE_PORT}
    <<: *logging

  # curl -X POST https://ton.DOMAIN.net/jsonRPC -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":"1","method":"getMasterchainInfo","params":{}}'
  ton-http-api:
    build:
      context: ./ton-http-api
      dockerfile: Dockerfile.api
    image: ton-http-api:local
    pull_policy: never
    restart: unless-stopped
    environment:
      - TON_API_CACHE_ENABLED=${TON_API_CACHE_ENABLED:-0}
      - TON_API_LOGS_JSONIFY=${TON_API_LOGS_JSONIFY:-0}
      - TON_API_LOGS_LEVEL=${TON_API_LOGS_LEVEL:-INFO}
      - TON_API_TONLIB_LITESERVER_CONFIG=/shared/local.config.json
      - TON_API_TONLIB_KEYSTORE=/tmp/ton_keystore/
      - TON_API_TONLIB_PARALLEL_REQUESTS_PER_LITESERVER=${TON_API_TONLIB_PARALLEL_REQUESTS_PER_LITESERVER:-50}
      - TON_API_TONLIB_REQUEST_TIMEOUT=${TON_API_TONLIB_REQUEST_TIMEOUT:-10}
      - TON_API_GET_METHODS_ENABLED=${TON_API_GET_METHODS_ENABLED:-1}
      - TON_API_JSON_RPC_ENABLED=${TON_API_JSON_RPC_ENABLED:-1}
      - TON_API_ROOT_PATH=${TON_API_ROOT_PATH:-/}
      - TON_API_WEBSERVERS_WORKERS=${TON_API_WEBSERVERS_WORKERS:-1}
      - TON_API_GUNICORN_FLAGS=${TON_API_GUNICORN_FLAGS:-}
    volumes:
      - shared:/shared
    healthcheck:
      test: curl -sS http://127.0.0.1:8081${TON_API_ROOT_PATH:-/}healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 24h
    labels:
      - traefik.enable=true

      # rpc
      - traefik.http.routers.${RPC_HOST:-ton}.service=${RPC_HOST:-ton}
      - traefik.http.routers.${RPC_HOST:-ton}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-ton}.rule=Host(`${RPC_HOST:-ton}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-ton}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-ton}lb.service=${RPC_HOST:-ton}
      - traefik.http.routers.${RPC_HOST:-ton}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-ton}lb.rule=Host(`${RPC_LB:-ton-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-ton}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-ton}.loadbalancer.server.port=8081
      - traefik.http.services.${RPC_HOST:-ton}.loadbalancer.healthcheck.path=${TON_API_ROOT_PATH:-/}healthcheck
    depends_on:
      ton:
        condition: service_started
    <<: *logging

volumes:
  ton:
  mytoncore:
  shared:
