x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  ton-node:
    build:
      context: ./ton
      dockerfile: Dockerfile
    image: ton:fixed
    pull_policy: never
    restart: unless-stopped
    ports:
      - ${VALIDATOR_PORT}:${VALIDATOR_PORT}/udp
      - ${LITESERVER_PORT}:${LITESERVER_PORT}/tcp
    tty: true
    volumes:
      - ton:/var/ton-work
      - mytoncore:/usr/local/bin/mytoncore
    environment:
      PIP_BREAK_SYSTEM_PACKAGES: 1
      TON_BRANCH: ${TON_BRANCH}
      GLOBAL_CONFIG_URL: ${GLOBAL_CONFIG_URL}
      IGNORE_MINIMAL_REQS: ${IGNORE_MINIMAL_REQS}
      MYTONCTRL_VERSION: ${MYTONCTRL_VERSION}
      DUMP: ${DUMP}
      MODE: ${MODE}
      ARCHIVE_TTL: ${ARCHIVE_TTL}
      STATE_TTL: ${STATE_TTL}
      SYNC_BEFORE: ${SYNC_BEFORE}
      VERBOSITY: ${VERBOSITY}
      CUSTOM_PARAMETERS: ${CUSTOM_PARAMETERS:-}
      PUBLIC_IP: ${PUBLIC_IP}
      VALIDATOR_PORT: ${VALIDATOR_PORT}
      LITESERVER_PORT: ${LITESERVER_PORT}
      VALIDATOR_CONSOLE_PORT: ${VALIDATOR_CONSOLE_PORT}
    <<: *logging
        
volumes:
  ton:
  mytoncore:
