ARG DOCKER_REPO=ghcr.io/ton-blockchain/ton-docker-ctrl
ARG DOCKER_TAG=latest

FROM ${DOCKER_REPO}:${DOCKER_TAG}

USER root

COPY ./docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod -R 755 /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
